# Generated by Django 2.2.2 on 2019-06-27 14:49

from django.db import migrations, models
import django.db.models.deletion
import template_pdf.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('format', models.CharField(choices=[('html', 'html'), ('odt', 'odt'), ('ott', 'ott'), ('oth', 'oth'), ('odm', 'odm'), ('otm', 'otm'), ('odg', 'odg'), ('otg', 'otg'), ('odp', 'odp'), ('otp', 'otp'), ('ods', 'ods'), ('ots', 'ots'), ('odc', 'odc'), ('odf', 'odf'), ('odi', 'odi')], max_length=255)),
                ('documenttemplate', models.FileField(upload_to=template_pdf.models.upload_path_handler)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
        ),
    ]
